import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Home, Search, User } from "lucide-react";
import Link from "next/link";
import Nav from "@/components/nav";
import { ThemeProvider } from "@/components/theme-provider";
import { Button } from "@/components/ui/button";
import {
	Tooltip,
	TooltipContent,
	TooltipProvider,
	TooltipTrigger,
} from "@/components/ui/tooltip";
import HomeHeader from "@/components/home-header";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
	modal,
}: Readonly<{
	children: React.ReactNode;
	modal: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ThemeProvider
					attribute="class"
					forcedTheme="dark"
					disableTransitionOnChange
				>
					<TooltipProvider>
						<div className="flex">
							<Nav />
							<div className="flex-1 px-6 py-4 flex flex-col gap-4">
								<HomeHeader />
								{children}
							</div>
						</div>
						{modal}
					</TooltipProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
